### ISSUE TITLE
Build SDK using latest build of ecj

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1203]
This is a follow up on https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1184 and also an item that we've tried to address before but failed (can't find the ticket).

*AS IS*:
- JDT **compiler** ([ecj](https://github.com/eclipse-jdt/eclipse.jdt.core/tree/master/org.eclipse.jdt.core.compiler.batch)) is an essential part of the SDK (even those who don't use Java directly use it inside the help application).
- We continuously change compiler with every release, adding both features / bug fixes.
- We have lot of compiler regression tests.
- **But** we update compiler used to build SDK **only after** producing milestone builds => usually 4 times during release cycle (3 months). The update is a manual process.
- We see that real life use of compiler (building SDK itself) may [discover corner cases](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1201) not covered by regression tests.

*TO BE*:

- We should change SDK build to build [ecj](https://github.com/eclipse-jdt/eclipse.jdt.core/tree/master/org.eclipse.jdt.core.compiler.batch) **first**, before starting "main" SDK build. [The org.eclipse.jdt.core.compiler.batch project](https://github.com/eclipse-jdt/eclipse.jdt.core/tree/master/org.eclipse.jdt.core.compiler.batch) is self contained Java library and has no dependencies to SDK.
- After the ecj is built we should run SDK build using exact that freshly compiled ecj build.
- There will be no need to manually updating ecj used to build SDK after each SDK milestone.
- We will catch compiler bugs earlier.
- We might see some "unstable" builds because the produced bytecode might change, but that shouldn't happen very often. At the end that would be less work because it would be not a "big bang" after each milestone like we saw in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1184.

This would allow us to "eat our own dog foot" with the compiler. Note: this is what Oracle does with building JDK itself every time.

*Technical notes*:
- Currently [ecj version is "hard coded"](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/77e5674499a806ae60fa184ff2516428a47540b4/eclipse-platform-parent/pom.xml#L89C34-L89C34) in [eclipse-platform-parent/pom.xml](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/77e5674499a806ae60fa184ff2516428a47540b4/eclipse-platform-parent/pom.xml):
```
    <cbi-jdt-repo.url>https://repo.eclipse.org/content/repositories/eclipse-staging/</cbi-jdt-repo.url>
    <cbi-ecj-version>3.35.0.v20230702-0608</cbi-ecj-version>
```
I personally have no idea how to do that with maven, but I assume something like below + some shell script change that triggers the SDK build and sets variables would do the trick:
```
    <cbi-jdt-repo.url>${local_ecj_build_target_directory_repo}/</cbi-jdt-repo.url>
    <cbi-ecj-version>${local_ecj_build_version}</cbi-ecj-version>
```

Help is welcome.

**Comment by laeubi** [comment]
> * Currently [ecj version is "hard coded"](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/77e5674499a806ae60fa184ff2516428a47540b4/eclipse-platform-parent/pom.xml#L89C34-L89C34) in [eclipse-platform-parent/pom.xml](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/77e5674499a806ae60fa184ff2516428a47540b4/eclipse-platform-parent/pom.xml):

Just as a general note you can always override properties in maven with `-D<property name>` so in this case `-Dcbi-ecj-version=1234` for example, so one don't need any shellscripts at all!

Also maven supports using local build artifacts so there is no need to reference a repository at all if you build it beforehand, so it could work to build it before, **BUT** if we assume that

1. JDT deploys snapshot builds to `https://repo.eclipse.org/content/repositories/<jdt or whatever>`
2. we are fine to use the latest deployed version instead of one build with this run (this is how Tycho snapshots work)

one could simply use the snapshots repository instead and a version range like `<cbi-ecj-version>(3.35.0,4.0.0-SNAPSHOT)</cbi-ecj-version>` but the maven docs is a bit unclear on how to include snapshots.

Another question would be if we only want it on the SDK build or also allow it for users that run the usual aggregator builds?

**Comment by iloveeclipse** [comment]
> BUT if we assume that JDT deploys snapshot builds to https://repo.eclipse.org/content/repositories/<jdt or whatever>

No, this deployment is manual. Point here is to automate everything.

> so one don't need any shellscripts at all!

There should be some way to "discover" the ejc version used - which may change from build to build. How to do that with maven?

> Another question would be if we only want it on the SDK build or also allow it for users that run the usual aggregator builds?

**Ideally** this would be aggregator build itself, because that is what users (like Advantest) do.

**Comment by laeubi** [comment]
> No, this deployment is manual. Point here is to automate everything.

If you add `deploy` to the maven goals it can deploy it automatically, that's how Tycho currently do it here:
https://github.com/eclipse-tycho/tycho/blob/edc419c7942a4f4db491537c3a7fb1a8f8d93739/Jenkinsfile#L35

> There should be some way to "discover" the ejc version used - which may change from build to build. How to do that with maven?

It depends a bit but you can use a version range with maven as well, or you can reference a SNAPSHOT version, or you can pass the version on the commandline (e.g. using 99.99.99 as a fixed string)

> Ideally this would be aggregator build itself, because that is what users (like Advantest) do.

I'll try out some things the next days if no one else already came up with a solution.

**Comment by laeubi** [comment]
And it *might* work to exploit using `LATEST` as a version, this is forbidden for plugins, but as ejc is a dependency it might still work here.

**Comment by iloveeclipse** [comment]
> If you add deploy to the maven goals

I think if we can get it with aggregator build and use snapshot version we would not need any additional deployment. I actually want aggregator build, because this is what I do every week and I will have there latest ecj too.

One thing I've not mention: ecj snapshot itself can be built with javac or with previously released ecj version, but then it can be used to build itself. Don't know if that is doable with maven.

**Comment by laeubi** [comment]
> We should change SDK build to build [ecj](https://github.com/eclipse-jdt/eclipse.jdt.core/tree/master/org.eclipse.jdt.core.compiler.batch) first, before starting "main" SDK build. [The org.eclipse.jdt.core.compiler.batch project](https://github.com/eclipse-jdt/eclipse.jdt.core/tree/master/org.eclipse.jdt.core.compiler.batch) is self contained Java library and has no dependencies to SDK.

Just for completeness, it is not completely selfcontained, it [requires the parent](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/abac2b3aee38ce4473c2958b15c969a98e0808e3/org.eclipse.jdt.core.compiler.batch/pom.xml#L14) and that requires the [the sdk parent](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/abac2b3aee38ce4473c2958b15c969a98e0808e3/pom.xml#L15).

But I think it could possibly be made an independent project, and then one might do the following:

`mvn clean install -f org.eclipse.jdt.core.compiler.batch -Dqualifier=`

`mvn clean verify`

where the second then uses a version range for the compiler.batch dependency that pull the local installed ECJ...

**Comment by laeubi** [comment]
> One thing I've not mention: ecj snapshot itself can be built with javac or with previously released ecj version, but then it can be used to build itself. Don't know if that is doable with maven.

I could think about converting the compiler project to a plain maven project (**please thing about it a minute before discard such idea**) because of the following:

1. If it really is independent, we do not need Tycho/OSGi at all, so one could develop it as a "plain java project" and add the metadata afterwards
2. Such an artifact could be independently deployed/released and even referenced by other parts now, currently we are bound to the eclipse relese cycle and even it is possible its quite inconvenient to use "current snapshots"
3. m2e/pde has some recent improvements to even allow using such "autogenerated" bundles in the IDE
4. I think Oompf also already just fetches from the IBuilds what is required so unless one is really developing in that part it is not needed to import the project at all.
5. Usually its easier to find developers that can use java (+maybe some maven) instead of all the eclipse/pde/sdk stuff so maybe it would make contributions to the compiler itself easier
6. Compiling could simply use `javac` here

So this would also be something I can try to investigate here...

**Comment by iloveeclipse** [comment]
> I could think about converting the compiler project to a plain maven project

I have no idea what that technically would mean and what need to be changed / updated in that case

> please thing about it a minute before discard such idea

If build would produce same results / binaries and that would help this task here, why should anyone discard this idea? Or is there something that would break any of "usual" workflows to contribute to JDT?

**Comment by merks** [comment]
This thing ships as a bundle in the p2 repository too doesn't it?  I.e., org.eclipse.jdt.core.compiler.batch.  It's not that long ago that there was all kinds of special handling for publishing it to Maven central which is all cleaned up now...

**Comment by iloveeclipse** [comment]
Ed, org.eclipse.jdt.core.compiler.batch is a "usual" bundle that is shipped with SDK (and required by jdt or help) but can be used standalone as java library and so it is also shipped as separated download.

**Comment by merks** [comment]
Yes that’s the point. It is a bundle and not an unusual one.  So I’m not sure how it makes sense to make it a plain maven project. I just hope that doesn’t solve one problem while also creating a new one.

**Comment by iloveeclipse** [comment]
Ed, I have no maven knowledge. If the switching to plain maven project would break something it is of course not acceptable. But I assume if @laeubi makes that proposal he has an idea how that is supposed to work.

**Comment by laeubi** [comment]
@iloveeclipse is there some class in jdt batch compiler that can be called to find out the version of the compiler? I think it would be good to print the used compiler version in Tycho so one do not needs debug output or alike to know what compiler version is actually used.

We currently already have a line like

```
  getLogger().info("Compiling " + sourceFiles.length + " " + "source file" + (sourceFiles.length == 1 ? "" : "s")
                + " to " + destinationDir.getAbsolutePath());
```

and I would like to enhance this by:

```
  getLogger().info("Compiling " + sourceFiles.length + " " + "source file" + (sourceFiles.length == 1 ? "" : "s")
                + " to " + destinationDir.getAbsolutePath() + "using ECJ "+Main.getCompilerVersion());
```

or something similar... I think I can extract it somehow from the manifest data but wondered if there is already somewhere a compile time constant.

**Comment by iloveeclipse** [comment]
ecj prints version in compilation output anyway in first lines (not sure if extra argument needed), I see it in ant output.
If I remember right, Main is the entry point.

**Comment by laeubi** [comment]
Okay it seems to use `/org/eclipse/jdt/internal/compiler/batch/messages.properties` for this purpose!

**Comment by laeubi** [comment]
I played around a bit now on a very low level by installing a "RC" version in my local repository, but the problem is that the deployed maven artifact uses a different name (artifactid = `ecj`)

https://mvnrepository.com/artifact/org.eclipse.jdt/ecj

while the real maven build artifact is `org.eclipse.jdt.core.compiler.batch`, what is also on central but seems not updated:

https://mvnrepository.com/artifact/org.eclipse.jdt/org.eclipse.jdt.core.compiler.batch

@merks @mickaelistria cam we probably deploy the ecj at both locations or use `org.eclipse.jdt.core.compiler.batch` from now on and [relocate ecj](https://maven.apache.org/guides/mini/guide-relocation.html) to that?

**Comment by merks** [comment]
Why is it needed i both locations?  I don't think we can do that easily at all.  It's just one IU and each IU is installed to one set of coordinates?  

Besides, I see these:

https://repo1.maven.org/maven2/org/eclipse/jdt/ecj/
https://repo1.maven.org/maven2/org/eclipse/jdt/org.eclipse.jdt.apt.core/

But I don't actually see the batch compiler here in Maven central:

https://repo1.maven.org/maven2/org/eclipse/jdt/

So I don't think this is a problem that needs solving.

**Comment by laeubi** [comment]
> So I don't think this is a problem that needs solving.

So then please provide the solution that Tycho uses `ecj` artifact id and a local build produces `org.eclipse.jdt.core.compiler.batch` and how can override the first with the second then.

**Comment by merks** [comment]
Somehow that "please" sounds like a demand.  It's not clear why this problem can **only be solved** with a name change of the artifact  (which is disruptive to everyone and it intended "only" to solve a problem only for the Platform).  Another possible approach is to use which is updated every day (so only a very small lag):

https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/jdt/ecj/

**Comment by laeubi** [comment]
> Somehow that "please" sounds like a demand

Sure because you claimed there is no problem I assumed you know the solution (its not obvious for me even though I'm working with maven a lot).

>  It's not clear why this problem can only be solved with a name change of the artifact 

Because one actually "lie" on maven, here, if you look at the `pom.xml` ist claims the artifact has an ID of `org.eclipse.jdt.core.compiler.batch` while we deploy it with id `ecj` and there is no way in maven to say it should actually use another id if you want to override things (what we actually want here, replace the default version of the `ecj` artifact).

The `ecj` was required in the past because it was an embedded jar of `org.eclipse.jdt.core` and not a standalone artifact, but this has changed, so one should have either used `ecj` as the artifact id (what would work but is a bit uncommon in eclipse builds) or start deploy it under the new artifact id (like we do for all other bundles as well).

> (which is disruptive to everyone and it intended "only" to solve a problem only for the Platform)

It is not if we place a relocation https://maven.apache.org/guides/mini/guide-relocation.html maven will automatically relocate any request to the old ID, this is very common practice in maven.

> Another possible approach is to use which is updated every day (so only a very small lag):
> https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/jdt/ecj/

The problem is that you then somehow needs to know the version and when it comes available, therefore it was the demand to make it work directly, at best even in JDT build workflow itself I think, so I can only share some observations that currently make it quite hard to accomplish, this also affects already Tycho development where one needs special tricks e.g. manually deploy the produced jar into the local repository (see step 4):

https://github.com/eclipse-tycho/tycho/blob/master/CONTRIBUTING.md#running-with-a-locally-build-version-of-jdt-compiler

So the (maven) solution would be to deploy it under the correct group id, Tycho migrates to that new one, have an relocation for the old to not dissatisfy other users (or at least let them know) and then one can proceed with much less workaround using standard maven techniques.

**Comment by merks** [comment]
It's not my decision to make how JDT publishes its artifacts nor how it evolves those IDs/locations.  Nor am I personally affected by such a change, other than making sure that the maven publish scripts continue to work well, which isn't a big deal so not a reason for or against.

I still wonder if using snapshots cannot be made to work. I imagine that given ecj itself, and the other parts of JDT on which it depends, should be compiled with ecj itself, that one inevitably must use an existing version of ecj for that purpose.  Using the previous day's snapshot published version (that has the existing current artifact ID) could be workable, couldn't it?   Of course I don't have a deep understanding of the implications like you do...

**Comment by stephan-herrmann** [comment]
I believe the conflict between different names of ecj is an unavoidable result of the impedance mismatch between OSGi and maven. In OSGi the BSN must start with org.eclipse.jdt because we don't own any other prefix. In Maven-land there is a tradition of naming this same artifact "ecj" where only the groupId manifests the orgin from org.eclipse.jdt. OSGi has no concept of groupId. Forcing the eco system that consumes ecj via Maven to change their dependencies to org.eclipse.jdt.core.compiler.batch would be quite a disruption.

Whether maven relocation would smoothly bridge that mismatch I cannot say. Would it allow maven based consumers to keep depending on org.eclipse.jdt:ecj:SOMERANGE, where SOMERANGE covers versions from before and after the relocation? Would it continue storing the artifact as org.eclipse.jdt:ecj in local maven repos? I'm asking because I believe consumers via maven should never be confronted with the name org.eclipse.jdt.core.compiler.batch.

It seems the only step that is missing for same-build results to be consumed by tycho is the renaming that is performed as part of https://github.com/eclipse-platform/eclipse.platform.releng/blob/master/publish-to-maven-central/SDK4Mvn.aggr right before release artifacts are published to Maven Central, and apparently also when deploying snapshots on repo.eclipse.org. But instead of renaming, can't tycho be instructed (for such SDK builds) to exclude ecj and instead to depend on that o.e.j.c.compiler.batch that has just been built in the same build? The contents is the same. Does tycho use the name "org.eclipse.jdt:ecj" **in code**?

**Comment by laeubi** [comment]
> I believe the conflict between different names of ecj is an unavoidable result of the impedance mismatch between OSGi and maven. In OSGi the BSN must start with org.eclipse.jdt because we don't own any other prefix. In Maven-land there is a tradition of naming this same artifact "ecj" where only the groupId manifests the orgin from org.eclipse.jdt. 

There is not an reason for a bundle in OSGi that it *must* start with org.eclipse.jdt  this is only a useful convention, also nothing in "maven land" forces you to use "ecj" (and actually most if not all platform deployed artifacts use the bsn instead any "shorter" name except the ejc artifact, because previously it was not an combined artifact.

> Whether maven relocation would smoothly bridge that mismatch I cannot say. 

You can simply try it out there are thousands of relocated artifacts on maven, for example https://mvnrepository.com/artifact/org.osgi/org.osgi.core

> Would it allow maven based consumers to keep depending on org.eclipse.jdt:ecj:SOMERANGE, where SOMERANGE covers versions from before and after the relocation?

Version ranges are discouraged by maven because it threaten the stability of your build.

> Would it continue storing the artifact as org.eclipse.jdt:ecj in local maven repos

Why should that matter at any time where it is finally stored as long as maven find it?

>  I'm asking because I believe consumers via maven should never be confronted with the name org.eclipse.jdt.core.compiler.batch.

Why do you believe that? As explained this is a usual maven technique part of maven core.

>  But instead of renaming, can't tycho be instructed (for such SDK builds) to exclude ecj and instead to depend on that o.e.j.c.compiler.batch that has just been built in the same build? The contents is the same. Does tycho use the name "org.eclipse.jdt:ecj" in code?

It is not Tycho, it is maven, and no one can't instruct maven to use something completely different thing here.

Each maven-plugin (and tycho is a maven plugin) has a set of declared dependencies, for the compiler part Tycho has the following dependency:

```
<dependency>
	<groupId>org.eclipse.jdt</groupId>
	<artifactId>ecj</artifactId>
       <version>....</version>
</dependency>
```

So if you are not happy with `<version>....</version>` you can override the dependency with another version (what the SDK build does) but it has to match for maven to exchange the declared default one, you can even add _other_ dependencies here but this will be additive here and not replace the other one.

**Comment by iloveeclipse** [comment]
Just a note: I believe this discussion moved to a wrong direction.

The goal is not to change any names, maven coordinates or deployment of ecj in any way.

The goal is to compile SDK with ecj build produced directly from sources. This ecj build must not be a valid maven/p2/whatever artifact, it can be named "the_ecj_build_of_the_day" and does not need to be published.

I might technically not understand how maven / tycho can do that, but with old good ant I would simply build ecj from sources with javac, package that as jar and use this jar to build the rest of SDK, including a "proper" ecj build.

The "the_ecj_build_of_the_day" could be simply thrown away after the SDK build that would produce current "expected" ecj artifact, as before.

**Comment by stephan-herrmann** [comment]
A side note:

> with old good ant I would simply ...

my personal interest in seeing where this issue moves is: with ant/pde build, the Object Teams project has been doing this for many, many years: build the compiler, than build everything with that fresh compiler. If s.o. could prove an easy route to achieve the same with maven I might even consider migrating to tycho :)

Back to the SDK build:

> The goal is not to change any names, maven coordinates or deployment of ecj in any way.

I agree. OTOH, the current workflow *does* contain a renaming step: when org.eclipse.jdt.core.compiler.batch is published to maven as org.eclipse.jdt:ecj, from where it is consumed by tycho. Thus I would think the natural question is: how can this renaming happen right when the result of build phase 1 is installed into the local maven repo. Using the cbiAggregator seems a bit oversized for this, but I would think that maven experts have lots of tools to tweak the behavior of `mvn install`, no?

**Comment by stephan-herrmann** [comment]
> It is not Tycho, it is maven, and no one can't instruct maven to use something completely different thing here.

Sorry, I keep forgetting that `<exclusions>` works only for indirect dependencies. Maven has so many options, but time and again the combination that I'd need, isn't supported :(

**Comment by stephan-herrmann** [comment]
Wait, can't we just maintain two separate poms with different coordinates. First do

```
cd org.eclipse.jdt.core.compiler.batch
mvn install -f pom_ecj.xml
``` 

which installs org.eclipse.jdt:ecj into the local maven repo,

then start the regular build.

**Comment by stephan-herrmann** [comment]
Pitfalls with the `pom_ecj.xml` approach:
* tycho insists that artifactId in pom and bsn in MANIFEST are the same
 => temporarily rewrite MANIFEST.MF, or can tycho be told to use MANIFEST.MF from a different location?
* ecj does have one dependency (from build.properties): ant
 => what is needed to tell tycho where to find it? Can `platform:/plugin/org.apache.ant/lib/ant.jar` be made to work, or some other tweak in pom?

Other than that this doesn't look too hard.

**Comment by stephan-herrmann** [comment]
I have a `pom_ecj.xml`, that should go a long way.
* I had to manually change bsn in MANIFEST.MF to 'ecj'
* In build.properties I removed the reference to ant
* In the tycho-compiler-plugin section I tried to exclude `**/JDTCompilerAdapter.java` to avoid the need for ant.

The first two steps should be possible as rewriting with some maven plugin, no?

Unfortunately, the last part doesn't have any influence on tycho, here's what I tried:
```
			<plugin>
				<groupId>>org.eclipse.tycho</groupId>
				<artifactId>tycho-compiler-plugin</artifactId>
				<version>${tycho.version}</version>
				<configuration>
					<excludes>
						<exclude>**/JDTCompilerAdapter.java</exclude>
					</excludes>
				</configuration>
			</plugin>
```


I'd show that little pom, but I haven't yet found a way to persuade github to upload any of my files, you'll just have to believe me :) 
_(yes, I know that github rejects *.xml, but it also rejects *.patch and *.PATCH contrary to its error message, so I don't believe github any more)._

I'll stop my experiments at this point.

**Comment by laeubi** [comment]
So instead of doing a small and easy fix we now try to rewrite stuff, using ant and other fragile things... I fear I can't help on this topic...

**Comment by iloveeclipse** [comment]
> So instead of doing a small and easy fix

If you have a proposal that is small and easy and does what is requested, please create a PR.
I personally don't care if it is done via maven, ant, make or whatever, the technology to be used is irrelevant if it does the job.

**Comment by stephan-herrmann** [comment]
@laeubi before you push a relocation based solution some more questions.

To be honest I have seen some artifacts change name over time (incl. tycho), but I never saw it transparently handled by relocation. That's why I would need a lot of explanations, before I can trust this approach. I'm willing to learn.

(I envy people like @iloveeclipse who manage to stay away from maven :) ).

>> Would it allow maven based consumers to keep depending on org.eclipse.jdt:ecj:SOMERANGE, where SOMERANGE covers versions from before and after the relocation?
>
> Version ranges are discouraged by maven because it threaten the stability of your build.

I've heard this many times, but I'm still puzzled: Discouraging a concept is one thing (why then didn't they just remove it from maven?), but using that reason as an excuse to cause arbitrary havoc on people who so far managed to use that concept in a meaningful way - that is not how I would like to deal with users or adopters.

To cut this discussion short let me rephrase my question. Let's just say downstream has this in their pom:
```
<dependency>
   <groupId>org.eclipse.jdt</groupId>
   <artifactId>ecj</artifactId>
   <version>${ecj.version}</version>
</dependency>
```
and they want to select the ecj version by providing that version property, eg. from the command line. Will they transparently get the correct version, even if it's actually called org.eclipse.jdt.core.compiler.batch?

> You can simply try it out there are thousands of relocated artifacts on maven, for example https://mvnrepository.com/artifact/org.osgi/org.osgi.core

Mh, when I look at https://repo1.maven.org/maven2/org/osgi/org.osgi.core/ that project looks dead. How am I to know what newer versions exist? Anything that tells any consumer of ecj that we stopped publishing new versions sounds like a no-go, if you ask me.

So far I'm more confident that we can code 10 or 20 solid lines of build code, rather than predicting how a name change affects the entire community. And this I mean both in technical terms as well as in terms of branding.

**Comment by stephan-herrmann** [comment]
And another correction:

> while the real maven build artifact is org.eclipse.jdt.core.compiler.batch, what is also on central but seems not updated:
> 
> https://mvnrepository.com/artifact/org.eclipse.jdt/org.eclipse.jdt.core.compiler.batch

No, that's not the real artifact. It's not even on maven central, nor can I access that repository. I'd call it an accident that it is listed there. Certainly not the doing of any committer within the Eclipse community.

**Comment by iloveeclipse** [comment]
The only reason this ticket was creted was to make sure we can find compiler bugs as soon as possible.
We don't have problems with ecj deployment or naming.

To achive the one and only goal of this ticket it should be enough to build the compiler **with any name we like** and **with any possible technology** and **somehow** tell maven that SDK build that follows should use that "ecj_build_of_the_day".

Isn't possible to run a trivial build of ecj as very first task, save it with some "ecj_build_of_the_day" id locally and use that id for compilation of following SDK tasks? It is totally irrelevant how this library should be named because it will never be used by anyone else. If maven can't compile libraries if their manifests differ from pom ids, let copy ecj code to a temp directory and just use different manifest, only for that build. Or even have a dedicated directory containing nothing else as a faked manifest and pom files and copy (or link) there the rest of ecj sources before build.

**Comment by stephan-herrmann** [comment]
[build-as-ecj.zip](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/files/11992362/build-as-ecj.zip)

Unpack this zip in the root of jdt-core's git working tree, i.e., in the parent of org.eclipse.jdt.core.compiler.batch.

From that same directory invoke `./org.eclipse.jdt.core.compiler.batch/scripts/build-as-ecj.sh`

Before doing so, you may want to set TEMP and/or MAVEN to smth useful on your system.

Result: the local maven repo will hold  `org/eclipse/jdt/ecj/ecj-3.35.0-SNAPSHOT.jar` with the latest and greatest bits (except that it contains no ant-support, which we simply don't care about here).

When tycho is configured to use ecj with that version, it should pick up this exact compiler for subsequent build steps, right?

I think it's good when manifest, build.properties, and pom are hosted by jdt.core, should anything need to be aligned with the originals (should be rare, perhaps the tycho version).

For the shell script perhaps releng.aggregator is the better place (with a tiny adjustment in line 7, the check for correct invocation location :)).

Does s.o. want to play with it before we proceed?

Should I push the jdt parts so next experiments can start right in the aggregator?

If `build-as-ecj` sounds obscure, we might call it `build-bootstrap-compiler`.

**Comment by laeubi** [comment]
> Result: the local maven repo will hold org/eclipse/jdt/ecj/ecj-3.35.0-SNAPSHOT.jar with the latest and greatest bits (except that it contains no ant-support, which we simply don't care about here).

And except that one now needs to maintain two manifest versions, two `build.properties`, and two `pom.xml` files ... also this only works on linux/mac thats why I suggested a soloution that only relies on maven itself.

> When tycho is configured to use ecj with that version, it should pick up this exact compiler for subsequent build steps, right?

This *when* is exactly the point, we already can do this, but we don't want to "configure" it it should happen automatically.

> Should I push the jdt parts so next experiments can start right in the aggregator?

Actually you can experiment with a local clone or even with a local jdt copy, but there is not much to experiment with as this will require addjusting the Jenkins build script.

> Does s.o. want to play with it before we proceed?

If we want to use "script magic" instead of proper maven ways you actually don't need all this you can do (as described here https://github.com/eclipse-tycho/tycho/blob/master/CONTRIBUTING.md#running-with-a-locally-build-version-of-jdt-compiler)

```
mvn clean package -f org.eclipse.jdt.core.compiler.batch
mvn install:install-file -N -Dfile=$(ls org.eclipse.jdt.core.compiler.batch/target/org.eclipse.jdt.core.compiler.batch-*-SNAPSHOT.jar | head -n 1) -DgroupId=org.eclipse.jdt -DartifactId=ecj -Dversion=99.99.99.ecj_build_of_the_day -Dpackaging=jar
mvn clean verify -Dcbi-ecj-version=99.99.99.ecj_build_of_the_day
```

The you will see (debug output enabled):

```
[DEBUG] Populating class realm plugin>org.eclipse.tycho:tycho-compiler-plugin:4.0.0
[DEBUG]   Included: org.eclipse.tycho:tycho-compiler-plugin:jar:4.0.0
[DEBUG]   Included: org.eclipse.jdt:ecj:jar:99.99.99.ecj_build_of_the_day
....
[DEBUG] properties used:
[DEBUG] buildId: I20230709-0455
[DEBUG] buildTimestamp: 20230709-0455
[DEBUG] buildType: I
[DEBUG] cbi-ecj-version: 99.99.99.ecj_build_of_the_day
```

**Comment by laeubi** [comment]
> I think it would be good to print the used compiler version in Tycho

Done with
- https://github.com/eclipse-tycho/tycho/pull/2615

**Comment by laeubi** [comment]
> you can do (as described here

I think this can be even more streamlined I have created
- https://github.com/eclipse-tycho/tycho/pull/2616

then it becomes

```
mvn clean package -f org.eclipse.jdt.core.compiler.batch -DjarName=ecj_build_of_the_day 
mvn install:install-file -N -Dfile=org.eclipse.jdt.core.compiler.batch/target/ecj_build_of_the_day.jar -DgroupId=org.eclipse.jdt -DartifactId=ecj -Dversion=99.99.99.ecj_build_of_the_day -Dpackaging=jar
mvn clean verify -Dcbi-ecj-version=99.99.99.ecj_build_of_the_day
```

still requires some non trivial maven invocations ...

**Comment by laeubi** [comment]
Scripted solution as code:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1207

**Comment by iloveeclipse** [comment]
@merks , @stephan-herrmann : since you seem to be familiar with maven (at least more than me), could you please review https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1221? This seem to be required for this task.

@laeubi : how https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1221 will be used in aggregator?

**Comment by merks** [comment]
The deletes are for already-commented-out stuff and the additions look simple, correct, and elegant.  👍

**Comment by laeubi** [comment]
> @laeubi : how https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1221 will be used in aggregator?

See "How to test" in the ticket

- run `mvn clean install -f org.eclipse.jdt.core.compiler.batch -DlocalEcjVersion=99.99`
- run aggregator build with `mvn clean verify -Dcbi-ecj-version=99.99`

**Comment by merks** [comment]
Compliments on the elegant solution!

**Comment by iloveeclipse** [comment]
> > @laeubi : how [eclipse-jdt/eclipse.jdt.core#1221](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1221) will be used in aggregator?
> 
> See "How to test" in the ticket
> 
> * run `mvn clean install -f org.eclipse.jdt.core.compiler.batch -DlocalEcjVersion=99.99`
> * run aggregator build with `mvn clean verify -Dcbi-ecj-version=99.99`

Could you please create a PR?
I've merged https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1221 so I assume it should be possible to run SDK build that uses this approach immediately .

**Comment by stephan-herrmann** [comment]
Somewhere above @laeubi mentioned the following as a problem:

> Just for completeness, it is not completely selfcontained, it [requires the parent](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/abac2b3aee38ce4473c2958b15c969a98e0808e3/org.eclipse.jdt.core.compiler.batch/pom.xml#L14) and that requires the [the sdk parent](https://github.com/eclipse-jdt/eclipse.jdt.core/blob/abac2b3aee38ce4473c2958b15c969a98e0808e3/pom.xml#L15).
> 
> But I think it could possibly be made an independent project, ...

Since you decided against a parent-less build, please keep in mind that building ecj before the actual SDK build may require one more (possibly tiny) tweak to make the parent known before it is built.

**Comment by laeubi** [comment]
Lets start with JDT core itself:
- https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1223

**Comment by laeubi** [comment]
I now also created a PR for the aggregator build here:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1208

for the "real" I-Build I will leave it as an exercise to the people familiar with all the shellscripts, I hope it should be quite clear to archive this there as well.

> Since you decided against a parent-less build, please keep in mind that building ecj before the actual SDK build may require one more (possibly tiny) tweak to make the parent known before it is built.

If it is a subproject build (e.g. jdt) the parent is consumed from the snapshot repository with the `-Pbuild-individual-bundles` profile, for the aggregator build the parent is loaded directly from the aggregator. And as the goal is to not change anything substantial I decided to not make any adjustments here.

**Comment by iloveeclipse** [comment]
Summary so far, thanks to @laeubi work we have following:
- https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1223 change is merged so Jenkins builds will use compiler built from sources to run JDT core build and tests.
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1208 is merged, so SDK aggregator build (with no tests) uses compiler built from sources.
- > for the "real" I-Build I will leave it as an exercise to the people familiar with all the shellscripts, I hope it should be quite clear to archive this there as well.

- @akurtakov or @sravanlakkimsetti, may be you have time to complete this work?

**Comment by sravanlakkimsetti** [comment]
I think adding 
```
mvn clean install -pl :eclipse-sdk-prereqs,:org.eclipse.jdt.core.compiler.batch -DlocalEcjVersion=99.99 -Dmaven.repo.local=$LOCAL_REPO
```
at https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/be625f4eb9c69dffa9106332f31b2a9fb7fbf67e/cje-production/mbscripts/mb220_buildSdkPatch.sh#L34
should suffice for this

**Comment by sravanlakkimsetti** [comment]
@MohananRahul Can you please make a PR for this one?

**Comment by iloveeclipse** [comment]
@laeubi : I think we are done here, thanks.

Just few questions for better understanding:

1) The very first ecj build that is done before SDK build starts, is done with javac that is taken from JDK which is used to run maven build, right? Or is this somehow taken from some pom file? If later - from which one / where exactly?
2) The very first ecj build is not shipped with the built SDK / repository, we continue to ship ecj that is compiled during SDK build itself?

**Comment by sravanlakkimsetti** [comment]
> @laeubi : I think we are done here, thanks.
> 
> Just few questions for better understanding:
> 
> 1. The very first ecj build that is done before SDK build starts, is done with javac that is taken from JDK which is used to run maven build, right? Or is this somehow taken from some pom file? If later - from which one / where exactly?
The first one is built with ecj version mentioned in parent-pom.
> 2. The very first ecj build is not shipped with the built SDK / repository, we continue to ship ecj that is compiled during SDK build itself?
first ecj build is not shipped and it will be discarded once the SDK build is complete

**Comment by iloveeclipse** [comment]
> The first one is built with ecj version mentioned in parent-pom.

OK, thanks for clarification. So this has to be updated at least every release.
With that, I think we are done here.

Thanks everyone contributed to final solution!

**Comment by laeubi** [comment]
> The very first ecj build that is done before SDK build starts, is done with javac that is taken from JDK which is used to run maven build, right? Or is this somehow taken from some pom file? If later - from which one / where exactly?

It is build in the "normal way" with Tycho, the only difference is that we select a list of two projects (the target and the compile) to build instead of the whole stuff and pass a parameter for publish the result as a special version.

> The very first ecj build is not shipped with the built SDK / repository, we continue to ship ecj that is compiled during SDK build itself?

Yes, it is just installed in the local maven repository but the update-site is build with the regular build (at least that's how it is supposed to work).
