### ISSUE TITLE
Bundle 'org.jsoup' cannot be resolved

### ISSUE THREAD

**Issue by gireeshpunathil** [eclipse-platform/eclipse.platform.releng.aggregator#1276]
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/c0e2884f1f57233b7110e06a1eb54debec0c508a/eclipse.platform.releng.prereqs.sdk/eclipse-sdk-prereqs.target#L221-L226 

shows that the bundle is a dependency, yet I get this error when sourced this project into latest I build and attempted to build. I can confirm that the IDE does not have a feature or plugin named `org.jsoup`.

**Comment by merks** [comment]
What have you done to configure the target platform?

Are you using the automated setup?

https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#creating-an-eclipse-development-environment

That works for me:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/38012f4b-c044-43cf-9faa-e3570be3a530)

Even activating the *.target works for me:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/7cda344a-0dfd-4f1c-9b33-c252343888b0)

And even using running platform works:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/4dcfddf1-32d4-4c0e-b3ba-332a365e90a6)

There is certainly nothing that needs to be fixed in the aggregator's target platform.  Moreover, I can't even reproduce your problem.  More information is required.

**Comment by gireeshpunathil** [comment]
thanks @merks for the detailed description. Unfortunately, these steps do not help me! In my case, the `soup` bundle itself is missing in the installation:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/6447530/11dc5f1b-cc82-4c2c-a4e8-85b5a880c187)

Is there any additional step I need to carry out to source in this jar file?

**Comment by merks** [comment]
It comes back to my initial question, "what have you done to configure the target platform?"  I guess/assume nothing.  Given that that bundle isn't in your installation, you will have to do something.  I.e., active the target platform:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/426a6185-5b2c-441b-9c82-09d763128f1c)

Or use Oomph.  Choose Eclipse SDK Product:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/8758c031-ca21-4119-a196-e9af1654e262)

Choose project(s):

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/7add41e5-6047-41dc-a9b0-fb1c1434059d)

When all is done, no errors:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/f1e2fed3-865f-44c0-9d63-76d5d08e7d79)

**Comment by gireeshpunathil** [comment]
@merks - thanks.

> what have you done to configure the target platform?

I opted for `eclipse-sdk-prereqs` there is an indication that it points to some additional tools/bundles/frameworks to be installed into the target, but apparently it did not do those:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/6447530/a3e60c23-e568-479f-8a07-159f52fb93ef)

**Comment by merks** [comment]
In isolation, there are so many things missing from the target platform that it's a sea of red.  I.e., the target platform does not include all of the Eclipse dependencies, only the external 3rd party dependencies.  But org.jsoup works:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/fa3da3f5-51e5-4bfc-a949-05c31332f18e)

There is a good reason that Oomph provides automated setups as well as the targlet infrastructure: because it works for cases like this that don't really work well any other way and no one else tries to make it work any other way.

**Comment by akurtakov** [comment]
@gireeshpunathil Do you have m2e installed? Without it maven dependencies in target platform are not resolved.

**Comment by merks** [comment]
Yet another reason for using automated setups; it installs the required tools in the installation:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/14054a78-cba1-403d-8b3d-22c594b324fe)

**Comment by gireeshpunathil** [comment]
thanks @akurtakov and @merks for the help and pointers! I installed m2e and got the problem resolved. I never faced these issues when working with PDE, so assumed that installation of a bare I-build is sufficient for developing any components, looks like that is not the case. I will follow your comments to learn how to set up a complete dev env that work for all the components!

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/6447530/e4a61e26-28da-4b3d-9617-f84061c6475e)

**Comment by merks** [comment]
I'm glad you were finally successful.     😄
