### ISSUE TITLE
Publish Eclipse features also to Maven central

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.releng.aggregator#1421]
AFAICS we currently do not publish our features to Maven central. https://central.sonatype.com/search?q=org.eclipse.e4.rcp

A target platform can include features from Maven, see https://github.com/eclipse-m2e/m2e-core/pull/636 therefore it would be nice if we publish also our features to Maven so that a target platform can avoid using p2 update sites.

@merks IIRC you are handling the release to Maven? I hope that publishing the feature to Maven is a simple task, e.g., by just adding the artifacts to the publishing script.

**Comment by merks** [comment]
No, I doubt that is a simple task at all.  In addition, I don't see significant value in this that would justify the time investment from my personal perspective.  To my thinking, features are really only useful for installing a set of bundles into an Equinox runtime.  So I have no plans to invest time into such an effort.

**Comment by merks** [comment]
There's a bunch of stuff here:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/master/eclipse.platform.releng/publish-to-maven-central

And this set of jobs do the work:

https://ci.eclipse.org/releng/view/Publish%20to%20Maven/

**Comment by merks** [comment]
Keep in mind that nexus as a bunch of rules for what can be published; rules that are more difficult than those for publishing to repo.eclipse.org which lets you dump pretty much anything...

**Comment by merks** [comment]
Also keep in mind that the platform consumes features from other projects:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/3319e85f-d22f-45c8-b195-ad03f89a1d5f)

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/131422d7-1e91-45b8-a647-891a906e427d)

Without those also being on Maven central, I'm doubtful this will be generally useful.

**Comment by laeubi** [comment]
@merks I think deploy the plain feature *file* is not what one really wants alone but the generated pom should simply list all requirements (like its already done for a bundle) and then it will be pulled from maven central as well.

Nerveless the only requirements are source+javadoc where we already have feature source jars and for bundles we already deploy a dummy javadoc so I won't expect anything different compared to deploy a jar if it contains a "bundle" or "feature".

**Comment by vogella** [comment]
Thanks @merks looks at if features are currently explicitly excluded. [#==== remove features: ====](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng/publish-to-maven-central/CBIaggregator.sh#L120). 

Others are already publishing their feature, for example https://repo.eclipse.org/content/groups/jgit/org/eclipse/jgit/feature/org.eclipse.jgit/3.0.0.201305281830-rc2/

**Comment by merks** [comment]
What's actually published to Maven central appears to be much reduced:

https://repo1.maven.org/maven2/org/eclipse/jgit/

I have no plans to publish EMF's features to a Maven repository.

**Comment by vogella** [comment]
@merks @laeubi Do you know how we publish to https://repo1.maven.org/maven2/? I see that our features are also missing their.

**Comment by merks** [comment]
We only publish there **after** a release.

**Comment by vogella** [comment]
> We only publish there **after** a release.

Looks like https://ci.eclipse.org/releng/view/Publish%20to%20Maven/job/PublishPlatformToMaven/ runs regulary, I see it running at the moment

**Comment by merks** [comment]
It's almost as if you are not reading what I am writing.  That makes this time consuming. 

Please read what the job description says and please reread https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1421#issuecomment-1748729282

**Comment by merks** [comment]
I continue to get the sense that you have not read what I have written.  Moreover, you appear to be under the impression that correctly publishing features to a Maven repository is simply a matter of  editing one simple shell script.  In addition to that, you seem to believe that the best time to test this and to iron out inevitable problems is when the final publishing is actually being done.  Publishing correct final results is a vital final step in our release process, one for which we cannot risk mistakes because cannot un-publish mistakes.

I really must strongly advise you to please take a step back and consider carefully the tasks involved in making this happen.

To start with, have you ever opened these resources to understand what this means and what it does?

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/71be0120-c792-4abd-87c6-44dd29a6b9a6)

Someone will need to edit this file:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggr

That someone will need to understand in detail what this file means and that someone will be best off to understand the purpose of this file:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng/publish-to-maven-central/SDK4Mvn.aggran

and how its associated editor can be used to verify and analyze the aggregation definition.

Assuming we enhanced the aggregator to map features properly, assuming we configure all the mapping rules correctly for all the features, assuming we know how to massage feature artifacts into proper maven artifacts acceptable to Nexus, then we still have the problem that the Platform's features depends on features from EMF and ECF that are not published, so maybe we must assume too that only a subset of the "pure platform" features are to be published.

You see there are a significant number assumptions involved here and a significant number of prerequisite TODOs that will require a significant depth of understanding and a significant investment of time.

Are you prepared to make this **significant** investment?  Such an investment must take place at the start of a release cycle, not at the end...

**Comment by vogella** [comment]
> Are you prepared to make this significant investment? 

In my experience things in Eclipse world are only requiring a *significant* investment because we continue to use our non customized technology. I plan to learn more about publishing to Maven central and return to this issue. 

> Such an investment must take place at the start of a release cycle, not at the end...

I tend to agree here, but as you said, it cannot be tested before the release cycle..... One option here might be to publish the features under a different namespace, e.g. vogellacompany (effectively a fork which would not affect the Eclipse standard) and if this works apply the learning to Eclipse.

Thanks again for you kind response, @merks. I understand your concerns and of course respect them.

**Comment by laeubi** [comment]
One can deploy to a file based repository 

`mvn deploy -DaltDeploymentRepository=snapshot-repo::default::file:/tmp/test-repo`

also sonatype has staging repositories that can act as a playground.

**Comment by akurtakov** [comment]
IIRC Lars gave up on this one in another issue.
