### ISSUE TITLE
Build I20231220-1800 FAILED

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#1684]
See https://ci.eclipse.org/releng/job/Builds/job/I-build-4.31/53/console

`org.eclipse.equinox.common.tests` & `org.eclipse.osgi.tests` (at least) can't be compiled anymore because of missing `CoreTest` dependency.

`CoreTest` was removed via https://github.com/eclipse-platform/eclipse.platform/pull/1047

@HeikoKlare : please check if we can easily get rid from `CoreTest` dependency in equinox.

Till then I will prepare revert of https://github.com/eclipse-platform/eclipse.platform/pull/1047 for now, to get build running again.

**Comment by merks** [comment]
Yes, my workspace looks like this after a pull:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/1c9a11cc-bca2-495e-8abd-d994b5baa432)

**Comment by merks** [comment]
Maybe they can all just use TestCase like I tried for this one:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/d456e512-c7a6-4da2-a5ea-a736877f1a4c)

**Comment by HeikoKlare** [comment]
I'll have a look and either update the tests or revert the removal.

Interestingly, my (completely built) workspace does not show any compile errors and the type hierarchy did not show any sublasses of `CoreTest` in my workspace (which contains those test bundles). I'll also try to figure out the reasons for that JDT behavior.

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/755472/729f2a0a-f2df-439f-b735-113dc0578f20)

**Comment by HeikoKlare** [comment]
> Maybe they can all just use TestCase like I tried for this one:

I hope that too. CoreTest did only provide utility methods, so in case they are not used in Equinox, changing to `TestCase` should be easy.

**Comment by iloveeclipse** [comment]
@HeikoKlare : OK, thanks for quick response, I feared you are on vacation olready.
For the revert, the PR is here: https://github.com/eclipse-platform/eclipse.platform/pull/1059
But I will wait for your PR on equinox now.

**Comment by laeubi** [comment]
> I'll have a look and either update the tests or revert the removal.

Another option if it can't be done easily is to just _copy_ the old class into equinox!

**Comment by iloveeclipse** [comment]
> I'll also try to figure out the reasons for that JDT behavior.

Usually this happens if one disables autobuild. And that usually happens with Oomph tasks running at startup (with autobuild disabled on purpose) but the setting is not reverted or persisted by mistake.

**Comment by laeubi** [comment]
> and the type hierarchy did not show any sublasses of `CoreTest` in my workspace (which contains those test bundles).

I also have had such behavior in the past, the only solution back then was to clear the java index and perform a full clean build.

**Comment by HeikoKlare** [comment]
From what I have seen now, it should be quite easy to remove the dependency from Equinox tests. Still it will be some effort and should may be separated into multiple PRs, as those tests extensively (mis)use the `CoreTest.fail(String, Throwable)` utility to attach a message to a thrown exception. Since this results in a test failure instead of a test error, this is semantically wrong in most cases (as there actually was an error and no failure).
I will prepare PRs to improve the code and remove/replace the `fail` calls to finally get rid of `CoreTest` there, but for now I think its best to revert the removal by merging eclipse-platform/eclipse.platform#1059 to not be forced to adapt the Equinox tests in a hurry.
Temporarily adding `CoreTest` to `org.eclipse.osgi.tests` would also work, but since we should get rid of that class anyway and the revert in the Platform repo is ready to merge, I'd prefer to not introduce in intermediate solution.

Thanks also for the input concerning the JDT issue. Auto-build was enabled all the time and the sublasses in Equinox never appeared in the type hierarchy for the last weeks that I was working on that topic. The indexing issue may be the reason. We also face issues with the index once in a while but it's unfortunately very difficult to reproduce.

**Comment by iloveeclipse** [comment]
OK, I'm going to merge https://github.com/eclipse-platform/eclipse.platform/pull/1059 and will start IBuild after that.

**Comment by iloveeclipse** [comment]
Triggered https://ci.eclipse.org/releng/job/Builds/job/I-build-4.31/54/

**Comment by iloveeclipse** [comment]
https://download.eclipse.org/eclipse/downloads/drops4/I20231221-0400 is OK
