### ISSUE TITLE
 Latest org.eclipse.platform bundle is 4.31 not 4.32

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.releng.aggregator#2008]
- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

Apologies if this is a known issue, but my OCD got the better of me. ;-)

The latest I-builds of 4.32 have the org.eclipse.platform bundle at version 4.31 not 4.32. For example:

https://www.eclipse.org/downloads/download.php?file=/eclipse/updates/4.32-I-builds/I20240503-1800/plugins/org.eclipse.platform_4.31.200.v20240503-1800.jar

https://www.eclipse.org/downloads/download.php?file=/eclipse/updates/4.32-I-builds/I20240503-1800/plugins/org.eclipse.platform.source_4.31.200.v20240503-1800.jar

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by merks** [comment]
In the past, folks like @laeubi and @MohananRahul  did an increment at the start of the release cycle:

![image](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/assets/208716/5aeb87b7-e508-4bfa-abff-82c0a0307552)

But the two most recent commits by @HeikoKlare  and @jukzi  only increment the micro version by 100.


@akurtakov 

I suppose our process for what to increment at the beginning of a release cycle can overlook something...

**Comment by HeikoKlare** [comment]
I am sorry for applying a "faulty" version bump to `eclipse.platform`. I guess the missing version bump for the 4.32 stream was because of the micro version increment, as the update for a new release cycle is probably done by matching the previous release version (in this case 4.31.0, so it did not match 4.31.100)?

Even though the process for what to increment at the beginning of a release cycle _could_ consider this, I think it would be even better to make it more explicit that `eclipse.platform` must not have a micro version increment (or even forbid that by tooling). I have probably overlooked this unnecessary increment when applying a batch correction of `build.properties` files, because this plug-in does not / cannot use API tools in PDE/Tycho to complain about that unnecessary version increment (in addition to unallowed micro version increments for `eclipse.platform` being kind of implicit knowledge).

Maybe we could ...
* add an according GitHub check that forbids micro version changes to `eclipse.platform` for PRs?
* add something to the plug-in that makes API tools applicable (i.e., something that we change for each release requiring a minor version bump)? But this may result in "dummy code" just to apply tooling, which is not that good either.

**Comment by iloveeclipse** [comment]
Let bump the version now to `4.32` and add the note to the "prepare release" checklist which I can't find now on https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/wiki

@sravanlakkimsetti : could you give a hint, which wiki is for release tasks?
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/wiki/Checklist
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/wiki/Releng-Tasks
