### ISSUE TITLE
Requesting a Y-build

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-platform/eclipse.platform.releng.aggregator#2223]
Somehow magically, we have a few builds in https://download.eclipse.org/eclipse/updates/4.33-Y-builds/ but this doesn't look like it's driven by any automatic schedule, right?

Now in https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1587 jdt.ui wants to consume latest changes from BETA_JAVA23 of jdt.core.

Could a new Y-build please be triggered to unblock the above PR?

Is it actually possible for a JDT committer to manually trigger a Y-build when needed? Otherwise, moving forward, it would be nice if such builds ran regularly, e.g., daily, to avoid wait time between fixes in different components, and to detect when components are out of sync (e.g, due to incompatible state of merge from master).

@jarthana @MohananRahul

**Comment by HannesWell** [comment]
If I'm not mistaken Y-builds are defined in
https://ci.eclipse.org/releng/job/YPBuilds/job/Y-build-4.33/ and they do run automatically every two days.
But the last builds fails either because they ran out of memory (which unfortunately happens occasionally in the recent past) or failed due to https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/468#issuecomment-2287030825, but if I read your comment you fixed that.

I have now triggered another Y-build, but every Platform committer should have access to the RelEng Jenkins instance and should have the permission to press the `Build now` button (or in German `Jetzt bauen`) on the left side. I cannot tell if JDT committer automatically can do that too, but you could try it out.

**Comment by stephan-herrmann** [comment]
> ... they do run automatically every two days

that might suffice for now.

> ... failed due to https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/468#issuecomment-2287030825, but if I read your comment you fixed that.

@jarthana  did :)

> I have now triggered another Y-build

thanks!

> I cannot tell if JDT committer automatically can do that too, but you could try it out.

Unfortunately: no. Even when logged in there is no `Build now` button (my browser speaks English ... :) ).

**Comment by laeubi** [comment]
JDT is not platform (even though we build it in the aggregator).

**Comment by stephan-herrmann** [comment]
Build was successful, update site is here: https://download.eclipse.org/eclipse/updates/4.33-Y-builds/Y20240814-1330 and https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1587 builds fine using that update site.

Thanks @HannesWell !

**Comment by HannesWell** [comment]
> Thanks @HannesWell !

You're welcome :)

> JDT is not platform (even though we build it in the aggregator).

That's right. I just wasn't sure if the [`RelEng` JIPP](https://ci.eclipse.org/releng/)  is just associated with the Eclipse-Platform project that also has it's own JIPP (https://ci.eclipse.org/platform/). I though maybe it is associated to the [Eclipse top level project](https://projects.eclipse.org/projects/eclipse) when it comes to permissions (the releng JIPP is a big mixture anyways).
