### ISSUE TITLE
Windows tests do not run anymore

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#2468]
See https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4410#note_2840448

JVM path has to be updated for Windows build

**Comment by IamLRBA** [comment]
I would like to contribute to this issue please.

**Comment by HannesWell** [comment]
This particular issue is already fixed via https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2470.

In general we should look for ways where we can fully control the exact version of the JDK being used in I-build tests via configuration files in this repo or in the releng instance accessible by us developers, so that we can update it completely by our-self.

Ideally we would download the JDK by our-self (e.g. Temurin provides a nice API for that) and would be able to cache it on the test machines.
