### ISSUE TITLE
SDK tarballs for linux should not set LIBARCHIVE.creationtime

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse-platform/eclipse.platform.releng.aggregator#2529]
Is there a good reason, that tar balls for the linux platform generate `LIBARCHIVE.creationtime` entries?
Example: https://download.eclipse.org/eclipse/downloads/drops4/S-4.34M3-202411070510/download.php?dropFile=eclipse-platform-4.34M3-linux-gtk-x86_64.tar.gz

Using the standard `tar` on linux (I'm on kubuntu) any read-operation on such a file causes huge floods of
```
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
```

I learned that these warnings can be ignored, but obviously using `tar tf` is not usable without addition hacks.

**Comment by stephan-herrmann** [comment]
Tar files were fine in this regard up until 4.25. First "bad" file is eclipse-SDK-4.26-linux-gtk-x86_64.tar.gz

**Comment by stephan-herrmann** [comment]
This had previously been filed (under e4 incubator, why?) as https://bugs.eclipse.org/bugs/show_bug.cgi?id=582413

**Comment by HannesWell** [comment]
This has already been reported in Tycho https://github.com/eclipse-tycho/tycho/issues/2586, but the actual cause is https://github.com/apache/commons-compress/pull/254 (as mentioned in the Tycho issue).

The problem has also been discussed on the tar/gnulib mailing list
- https://lists.gnu.org/archive/html/bug-gnulib/2024-03/msg00189.html
- https://lists.gnu.org/archive/html/bug-tar/2024-03/msg00014.html

but it looks like they haven't come to a conclusion yet.

It has also already been reported in https://github.com/eclipse-platform/eclipse.platform.releng/issues/147.
And https://github.com/eclipse-packaging/packages/issues/53 contains a workaround.

But I agree it's annoying, For example the in the I-build tests it looks like these message are responsible for a major part of the log content.

**Comment by laeubi** [comment]
> but it looks like they haven't come to a conclusion yet.

It would already help to print the same message only **once* :-\

**Comment by HannesWell** [comment]
[This ](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2530) had the desired effect. I can un-tar the latest I-build SDK for linux without any `Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'` message.
It also does appear much less in the logs (the previous releases eclipse-platform product is still used to provision installations) and the size of the linux log files went down from 20MiB per config to ~7MiB:
https://download.eclipse.org/eclipse/downloads/drops4/I20241111-1800/logs.php#console
https://download.eclipse.org/eclipse/downloads/drops4/I20241110-1800/logs.php#console
