### ISSUE TITLE
4.35 Y-Build - Build Failure since #19

### ISSUE THREAD

**Issue by SougandhS** [eclipse-platform/eclipse.platform.releng.aggregator#2658]
see : https://ci.eclipse.org/releng/job/YPBuilds/job/Y-build-4.35/
Build #.19, #.20 & #.21 Failed due to issues in equinox-sdk 4.35.0-SNAPSHOT & eclipse.platform.repository 4.35.0-SNAPSHOT

<img width="1221" alt="image" src="https://github.com/user-attachments/assets/e3b59884-f5f1-45a5-b285-1dc527647588" />

<img width="1384" alt="image" src="https://github.com/user-attachments/assets/5300d5e8-93fb-49dc-8672-07d98e295008" />

<br>
<img width="1404" alt="image" src="https://github.com/user-attachments/assets/6cfdc1e4-c6e2-4cba-9692-7ae5a49e30f5" />

log : https://ci.eclipse.org/releng/job/YPBuilds/job/Y-build-4.35/21/console
## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by HannesWell** [comment]
The last three Y-builds were again successful.
I'm not aware that any of the changes made in this repo recently fixed is, so many it was because they master branch was again merged into the Java-24 branch.

Anyways, I think this can be closed. 

In general it's probably a good idea to merge the master into the beta branch as a first attempt to fix build problems. Especially as there are currently many changes.

**Comment by SougandhS** [comment]
Thanks @HannesWell
