### ISSUE TITLE
[win] I-Build tests increased and taking longer since I20241216

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.releng.aggregator#2672]
+30 000 tests =>+20 min

![image](https://github.com/user-attachments/assets/7ecfd659-9f7d-41f0-a5ad-6f238190bcdc)
![image](https://github.com/user-attachments/assets/71a35a30-58ca-450c-9a10-4eb809a719ba)

Is that intentional?

**Comment by akurtakov** [comment]
Which job is that ?

**Comment by jukzi** [comment]
https://ci.eclipse.org/releng/job/AutomatedTests/job/ep435I-unit-win32-x86_64-java17/
![image](https://github.com/user-attachments/assets/55913e1f-4b57-4f07-878c-bd2800b19252)

**Comment by akurtakov** [comment]
That's expected. If you look at previous release https://download.eclipse.org/eclipse/downloads/drops4/R-4.34-202411201800/ you'll see linux tests on Java 21 having 30K+ tests compared to Java 17 tests . Tests for newer JVM were simply not executed on Windows due to running on Java 17.
The reason that you see the increase in the win java 17 job is because it's last run actually used Java 21 (https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/83a6341552c2e3563ee90068b25ebb80de96c365 ) but I forgot to rename the job (done via https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/1b89ba56c1df2842f1e86799dca84da539b8e8d5 ) as the setup is really cumbersome.

**Comment by akurtakov** [comment]
For the record there will be no more runs in https://ci.eclipse.org/releng/job/AutomatedTests/job/ep435I-unit-win32-x86_64-java17/ and new I-builds will fire https://ci.eclipse.org/releng/job/AutomatedTests/job/ep435I-unit-win32-x86_64-java21/ . Java 17 test jobs will stay for some time but will be removed after M1 to not cause confusion.

**Comment by jukzi** [comment]
But is it really needed to run JDT tests for JDK 11,17,20,21? I would say we can skip 20 as it is not LTS.

![image](https://github.com/user-attachments/assets/f537c638-a820-4201-a278-b54debdffd06)

**Comment by merks** [comment]
Skipping EOL versions would seem to make sense.  Better to test 23 than to test 20...

**Comment by jukzi** [comment]
its also the case for 
https://ci.eclipse.org/releng/job/AutomatedTests/job/ep435I-unit-win32-x86_64-java21/lastCompletedBuild/testReport/org.eclipse.jdt.core.tests.compiler.regression/TestAll/
![image](https://github.com/user-attachments/assets/4f7ce51b-2df5-4cef-b924-52178c438d3b)

**Comment by akurtakov** [comment]
Which versions to execute are controled by jdt.core not releng. E.g. the profiles in this bundle look totally random:
* Java 17 https://github.com/eclipse-jdt/eclipse.jdt.core/blob/17fc31849b5225c441e93a8cc7eec636cd05067f/org.eclipse.jdt.core.tests.compiler/pom.xml#L65 - 1.8, 14(!), 17 
* Java 21 https://github.com/eclipse-jdt/eclipse.jdt.core/blob/17fc31849b5225c441e93a8cc7eec636cd05067f/org.eclipse.jdt.core.tests.compiler/pom.xml#L149 - 1.8,17,19(!),21
*Useless Java 18, 19, 20 profiles IMO
* No execution of Java 11 tests
^^ Is for Maven running tests.
For I-builds what is run seems to come from https://github.com/eclipse-jdt/eclipse.jdt.core/blob/17fc31849b5225c441e93a8cc7eec636cd05067f/org.eclipse.jdt.core.tests.compiler/test.xml#L60 which is even bigger mystery to me who/what/when/where uses it.

It's similar state in o.e.jdt.core.tests.builder and and o.e.jdt.core.tests.model. The work for putting some sense into this will have to happen in jdt.core.
