### ISSUE TITLE
org.ow2.sat4j.pb has `Class-Path: org.sat4j.core.jar` causing non breaking log message when compiling

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.releng.aggregator#416]
The following warning is printed multiple times:
```
--- tycho-compiler-plugin:3.0.0-SNAPSHOT:compile (default-compile) @ org.eclipse.pde.api.tools.tests ---
12:26:44  [INFO] Compiling 200 source files to /home/jenkins/agent/workspace/I-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/eclipse.pde/apitools/org.eclipse.pde.api.tools.tests/target/classes
12:26:44  Failed to init Classpath for jar file /home/jenkins/agent/workspace/I-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/localMavenRepo/org/ow2/sat4j/org.ow2.sat4j.pb/2.3.6/org.sat4j.core.jar
12:26:44  java.nio.file.NoSuchFileException: /home/jenkins/agent/workspace/I-build-4.25/eclipse.platform.releng.aggregator/eclipse.platform.releng.aggregator/cje-production/gitCache/eclipse.platform.releng.aggregator/localMavenRepo/org/ow2/sat4j/org.ow2.sat4j.pb/2.3.6/org.sat4j.core.jar
```

Visible in e.g. https://ci.eclipse.org/releng/job/I-build-4.25/95/console .

**Comment by iloveeclipse** [comment]
Technical info: the errors are only printed, they don't break compilation.

They are now there because of https://github.com/eclipse-jdt/eclipse.jdt.core/pull/239 where I've fixed most of the places where errors were **silently** ignored by ecj, to help with analysis of https://github.com/eclipse-jdt/eclipse.jdt.core/issues/183.

To **fail** the build, `-Dorg.eclipse.jdt.propagate_io_errors=true` can be set on compiler JVM arguments.

**Comment by mickaelistria** [comment]
Thanks for the clarification @iloveeclipse . It's good to have those printed. I'll try to look at it soon to see whether it's a conf issue or a Tycho one. The path to the artifact seems to really miss the version part that's typical with Maven jars.

**Comment by mickaelistria** [comment]
This is caused by org.ow2.sat4j:org.ow2.sat4j.pb:2.3.6 bundle containing in its MANIFEST.MF `Class-Path: org.sat4j.core.jar` and ECJ tries to expand that to a location, which is invalid in that case.
@sat4j @danielleberre is `Class-Path: org.sat4j.core.jar` is still necessary, if not, could it be removed in future versions of sat4j?

**Comment by danielleberre** [comment]
This is used when running sat4j on the command line. But I also have all in one jars for that, so if needed I could remove it.

Those jars are produced by the ant script. I should probably have a distinct manifest file for that.

**Comment by danielleberre** [comment]
I created an issue upstream to take care of that: https://gitlab.ow2.org/sat4j/sat4j/-/issues/172

**Comment by akurtakov** [comment]
sat4j.pb.jar still has the line in question but Tycho no longer complains about it so nothing more to track here.
