### ISSUE TITLE
Migrate Releng Jenkins jobs to groovy/jenkinsfiles. 

### ISSUE THREAD

**Issue by SDawley** [eclipse-platform/eclipse.platform.releng.aggregator#568]
Currently much of https://ci.eclipse.org/releng/ only exists in Jenkins and has to be manually updated and maintained. 

I'd like to move as many of these scripts and configurations out of Jenkins as possible. My plan is to convert everything into groovy or jenkinsfiles and use Job-DSL to automatically create new jobs when we start a new release.

Job-DSL has been installed as per https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1918

This issue is to track my work/PRs and allow @sravanlakkimsetti or anyone interested a dedicated place to comment.

Current plan is to use the existing JenkinsJobs folder and expand on that. New jobs will be created in folders and shouldn't interfere with or overwrite the existing jobs. Once everything is working I can have Job-DSL recreate the views to show the new jobs and the old infrastructure can be removed.

How everything works so far:
- Variables like release/stream version, maintenance branches and supported jdk's will be stored in JobDSL.json
- Folders will be created under JenkinsJobs to match the current views in jenkins. Each job with have a groovy file with the build stages and parameters. Pipeline jobs  will need an additional jenkinsfile (currently I and Y builds).
- I've made a [seed job](https://ci.eclipse.org/releng/job/Create%20Jobs/) in jenkins that I will configure to pull this repo and check the JenkinsJobs folder. It will first create folders from FOLDER.groovy files (to match git folder structure) then create jobs. 
- Once everything is working I can add VIEW files that will move created jobs into views so the current jenkins layout will be maintained. 

Additional optimizations to look into after everything is migrated:
- [ ] Convert tests to matrix jobs
  - [ ] Rework results collection to use variables/parameters passed from the test job instead of parsing the job name
- [ ] Combine build machine cleanup scripts into a multi-configuration job
- [ ] Combine shared content in I and Y builds (and possibly P builds?)
- [ ] Combine shared configuration in releng scripts

**Comment by HannesWell** [comment]
The goal to move as much configuration as possible out of Jenkins and into some code under version control is a good one and I think that makes it simpler to understand and maintain the build infrastructure of Eclipse.

One point in that area I noticed recently is the configuration of the platform specific [Automated Tests](https://ci.eclipse.org/releng/view/Automated%20tests/) that run after the I-build.
At the moment those jobs are defined as pipeline job, where the declarative pipeline script is written into the Job configuration. Since those jobs basically only differ in the OS and Java version those scripts are highly redundant.
I wonder if it would be better to maintain if the automated tests are declared in an extra [Matrix-Stage](https://www.jenkins.io/doc/book/pipeline/syntax/#declarative-matrix) after the actual I-build replacing the `Trigger tests` stage.
Or would it then be impossible to define the kubernetes agents then?

Furthermore the `JenkinsJobs/Builds/I-build.groovy` and `Y-build.groovy` share a lot of content. I wonder if that could be generalized into an abstract script?

**Comment by akurtakov** [comment]
One suggestion here - do not try to achieve everything at once as the process could be quite fragile. So please go in smaller steps so I-builds are still produced regularly (even if some days it fails).

**Comment by SDawley** [comment]
@HannesWell theoretically converting all the tests into matrix jobs should be doable, but that would probably require changing how results collection works since it parses the job name for information. It's definitely something I'll look into after doing a first pass of moving everything into git, so I'll add it to the issue.

**Comment by HannesWell** [comment]
> @HannesWell theoretically converting all the tests into matrix jobs should be doable, but that would probably require changing how results collection works since it parses the job name for information. It's definitely something I'll look into after doing a first pass of moving everything into git, so I'll add it to the issue.

Great. Step-by-step is perfectly fine. I just wanted to mention/discuss it so that it is eventually considered (if possible). 👍🏽

Would it be possible to use some environment variable for result collection that is passed to the test-job? Or just use the corresponding matrix/axes variable within the job? Shouldn't those be available in each matrix-job?

**Comment by SDawley** [comment]
Created a helpdesk issue to see if we can get a webhook set up so that the seed job will run whenever there's a change to JenkinsJobs: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2090

For right now, it will run daily

**Comment by SDawley** [comment]
Created https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/629
Will merge once checks pass and rerun the tests.

Also the webhook got added so Create Jobs _should_ update the builds automatically when I merge.

**Comment by akurtakov** [comment]
checks will run the tests only via maven aka not test your change.

**Comment by SDawley** [comment]
OK, I'll merge now then.

**Comment by akurtakov** [comment]
@SDawley what's left here?

**Comment by SDawley** [comment]
Closing since all the major jobs (those that run regularly) have been switched to running from groovy files.
