### ISSUE TITLE
New Dependency Chain rcp -> batik -> xmlgraphics -> commons.logging

### ISSUE THREAD

**Issue by cdietrich** [eclipse-platform/eclipse.platform.releng.aggregator#651]
hi, is the new dependency chain

 Error:  Cannot resolve project dependencies:
Error:    Software being installed: org.eclipse.rcp.feature.group 4.26.0.v20221020-2202
Error:    Missing requirement: org.apache.xmlgraphics 2.7.0.v20221018-0736 requires 'java.package; org.apache.commons.logging [1.0.4,1.3.0)' but it could not be found
Error:    Cannot satisfy dependency: org.apache.batik.css 1.15.0.v20221018-0736 depends on: java.package; org.apache.xmlgraphics.java2d.color 2.7.0
Error:    Cannot satisfy dependency: org.eclipse.e4.rcp.feature.group 4.26.0.v20221020-2202 depends on: org.eclipse.equinox.p2.iu; org.apache.batik.css [1.15.0.v20221018-0736,1.15.0.v20221018-0736]
Error:    Cannot satisfy dependency: org.eclipse.rcp.feature.group 4.26.0.v20221020-2202 depends on: org.eclipse.equinox.p2.iu; org.eclipse.e4.rcp.feature.group [4.26.0.v20221020-2202,4.26.0.v20221020-2202]

intentional (aka is the new org.apache.xmlgraphics 2.7.0.v20221018-0736 in orbit as we want it or did unwanted changes sneak in)

https://github.com/itemis/xtext-reference-projects/pull/300/files

**Comment by merks** [comment]
I think this is all intentional and it appears to be in Orbit:

![image](https://user-images.githubusercontent.com/208716/198821751-76e948c9-2431-4635-a473-bed1b5bc99ba.png)

The logging requirement is satisfied by the version of logging (also available from Orbit):

![image](https://user-images.githubusercontent.com/208716/198821823-7e915ff8-6f97-481e-b8fe-884a31a5dfe0.png)

This was recently changed with the following comment:

Update Batik to 1.16

Fixes:
* CVE-2022-42890
* CVE-2022-41704
