### ISSUE TITLE
No test results summary since I20221114-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng.aggregator#668]
See https://download.eclipse.org/eclipse/downloads/drops4/I20221114-1800/

It says "3 of 6 integration and unit test configurations are complete." but there are no test results *summary* on the build page:

![image](https://user-images.githubusercontent.com/964108/201855948-daa14dc0-3caa-4aea-84f4-54065db426d1.png)

Going to the actual test results page we see the build results:

![image](https://user-images.githubusercontent.com/964108/201856111-b30021b8-e784-45e8-bb20-d57c803972c2.png)

Probably side effect of recent build script improvements, like https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/666

@SDawley : could you please check?

**Comment by SDawley** [comment]
This should be fixed. The jobs were updated while the tests were already running so Collect Results was run with the wrong parameters. I reran the failed results collection jobs with the new parameters and I20221114-1800 now has 6/6 results. Still investigating #669, I'd hoped to verify that this all worked without human intervention with tonight's I-Build but I'm waiting for https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2255 to be resolved since the releng jenkins is having the same issue.

**Comment by iloveeclipse** [comment]
@SDawley : still in RC 1 build.
https://download.eclipse.org/eclipse/downloads/drops4/I20221117-1330/
![image](https://user-images.githubusercontent.com/964108/202661250-4121fd7a-4c99-4749-bd67-d7223fbaecd1.png)

**Comment by SDawley** [comment]
I merged a fix and re-ran the results collection for ep426I-unit-cen64-gtk3-java17 for this mornings build.
The results summary appeared, so the table should be fully populated as of tonights build.
https://download.eclipse.org/eclipse/downloads/drops4/I20221123-0600/

**Comment by akurtakov** [comment]
https://download.eclipse.org/eclipse/downloads/drops4/I20221123-1800/ has 4 out of 6 showing already. Closing.
