### ISSUE TITLE
slf4j missing uses constraints

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-platform/eclipse.platform.releng.aggregator#682]
The SLF4J is missing uses constraints. This leads to runtime errors like this (I added line breaks for readability) if there are multiple versions of slf4j installed.

```
loader constraint violation: 
  when resolving method 'org.slf4j.ILoggerFactory org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()' 
  the class loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @3a07fd19 of the current class, 
    org/slf4j/LoggerFactory, and 
  the class loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @773560cf for the method's defining class, 
    org/slf4j/impl/StaticLoggerBinder, 
  have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
  (org.slf4j.LoggerFactory is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @3a07fd19,
       parent loader 'platform'; 
   org.slf4j.impl.StaticLoggerBinder is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @773560cf, 
       parent loader 'platform')
```

**Comment by jonahgraham** [comment]
A workaround is to make sure that only a single version of SLF4J is installed.

**Comment by HannesWell** [comment]
> A workaround is to make sure that only a single version of SLF4J is installed.

That should be the goal also to ensure the logging works correctly.
But having technical support to enforce this would be still good.

On the other hand that would make it impossible to use two libraries where one requires strictly slf4j<2 (because it has not yet updated its import-package ranges) and the other requires slf4j>=2. The logging will then likely be flaky, but if one does not care about that, it is not possible anymore.

**Comment by akurtakov** [comment]
Is there anything to do on releng side here or it can be closed?

**Comment by jonahgraham** [comment]
> Is there anything to do on releng side

I think so, the slf4j that platform now pulls in has no uses clauses (unlike the slf4j that orbit repackages). This leads to wiring errors.

I understand the move away from orbit, but if the upstream package is missing uses clauses and we encourage consumers of slf4j to use import package, then we should ensure that uses clauses exist.

**Comment by akurtakov** [comment]
I hope that someone will open issue against slf4j requesting uses clauses to be added.

**Comment by jonahgraham** [comment]
https://jira.qos.ch/browse/SLF4J-574

**Comment by HannesWell** [comment]
Thank you Jonah for string https://github.com/qos-ch/slf4j/pull/324.
Just adding it to have a cross-reference.

**Comment by akurtakov** [comment]
New slf4j version with Jonah's change has been released https://github.com/qos-ch/slf4j/compare/v_2.0.5...v_2.0.6 . Please provide the needed updates so we can finish this one.

**Comment by jonahgraham** [comment]
@HannesWell can you make this change in platform?

**Comment by ruspl-afed** [comment]
Does it mean that Platform is going to switch to SLF4J 2.x?

**Comment by HannesWell** [comment]
> @HannesWell can you make this change in platform?

Yes, I do. But after looking in more detail in your change I noticed that it for example changed the BSN. At the moment slf4j has now a mixtured of generating the manifest and using static manifest files under version control. I have started to prepare a follow-up on your change and plan to complete it this evening, that completely migrates to generating the manifests, thus removing all static manifest files.



> Does it mean that Platform is going to switch to SLF4J 2.x?

Yes, we do. See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/588

But I'm considering (and https://github.com/bndtools/bnd/pull/5477#issuecomment-1350622417 strengthened this consideration) to ask SLF4J to export its packages in a 1.7.x version and 2 version, so that libaries that import slf4j below version 2 can just use slf4j-2 without changes.

**Comment by HannesWell** [comment]
> > @HannesWell can you make this change in platform?
> 
> Yes, I do. But after looking in more detail in your change I noticed that it for example changed the BSN. At the moment slf4j has now a mixtured of generating the manifest and using static manifest files under version control. I have started to prepare a follow-up on your change and plan to complete it this evening, that completely migrates to generating the manifests, thus removing all static manifest files.

Created https://github.com/qos-ch/slf4j/pull/327.

**Comment by merks** [comment]
I noticed this resolution failure (in Tycho 4.0.0-SNAPSHOT) when trying to fully resolve the requirements of `slf4j-api` version 2.0.6

> Missing requirement: org.slf4j.api 2.0.6 requires 'osgi.extender; (&(osgi.extender=osgi.serviceloader.processor)(version>=1.0.0)(!(version>=2.0.0)))' but it could not be found

What is supposed to satisfy that requirement?

**Comment by HannesWell** [comment]
The  (Referenzen) Implementation of the OSGi ServiceLoader Mediator specification I usually use is Apache Aries SPI-fly:
- https://aries.apache.org/documentation/modules/spi-fly.html

- https://mvnrepository.com/artifact/org.apache.aries.spifly/org.apache.aries.spifly.dynamic.bundle
That should provide that capabilty.

**Comment by merks** [comment]
Okay, that helps!  With that included, it gets to this failure:

> Missing requirement: org.slf4j.api 2.0.6 requires 'osgi.serviceloader; (osgi.serviceloader=org.slf4j.spi.SLF4JServiceProvider)' but it could not be found

**Comment by HannesWell** [comment]
> Okay, that helps! With that included, it gets to this failure:
> 
> > Missing requirement: org.slf4j.api 2.0.6 requires 'osgi.serviceloader; (osgi.serviceloader=org.slf4j.spi.SLF4JServiceProvider)' but it could not be found

Do you have a recent SLF4J-provider in the TP? In case of Eclipse-Platform we probably want to only reference to no-op  provider and let actual application/product builds choose a suitable one for them:
https://mvnrepository.com/artifact/org.slf4j/slf4j-nop/2.0.6

**Comment by merks** [comment]
That fixes the problem!  You're the best.  🚀

**Comment by akurtakov** [comment]
Should this one be closed now?

**Comment by HannesWell** [comment]
> Should this one be closed now?

Unfortunately the metadata of the current slf4j-release are still different than before in same parts:

> > @HannesWell can you make this change in platform?
> 
> Yes, I do. But after looking in more detail in your change I noticed that it for example changed the BSN. At the moment slf4j has now a mixtured of generating the manifest and using static manifest files under version control. I have started to prepare a follow-up on your change and plan to complete it this evening, that completely migrates to generating the manifests, thus removing all static manifest files.

Therefore I'm not sure if we should use that version.
I created https://github.com/qos-ch/slf4j/pull/327 to fix that but that change was considered to large. As requested I created a reduced follow-up https://github.com/qos-ch/slf4j/pull/330, but that did not yet get any attention.
So if anyone of you can help to motivate the SLF4J-maintainer for the latter PR that would help.
Otherwise we have to go with the changed metadata.
