### ISSUE TITLE
Move I-build Windows tests to Java 17

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.releng.aggregator#756]
Java 17 is used to run tests for Mac (only this version) and on Linux (together with other versions) . As windows resources are limited and Java 17 is the latest LTS JVM and the fact that all EPPs are shipped with Java 17 it makes sense for Windows tests to be run with Java 17 and not Java 11.

**Comment by akurtakov** [comment]
@sravanlakkimsetti Would you please outline what I have to do to achieve that?

**Comment by akurtakov** [comment]
Related to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/755

**Comment by sravanlakkimsetti** [comment]
Here are the steps:
1. Raise a request with foundation to install java 17(temurin would suffice) on [windows test machine](https://ci.eclipse.org/releng/computer/qa6xd-win11/)
2. Update java links in the test job https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/JenkinsJobs/AutomatedTests/I_unit_win32_java11.groovy
3. Since test results publishing scripts parse the name of the job to list java version, you'll need to rename the test job to java 17 and update publishing scripts. The following scripts will need an update
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/affbb3a6d1fecebae0f55a5ae9fa9137f9c37d34/cje-production/scripts/publish.xml#L187
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.tychoeclipsebuilder/eclipse/publishingFiles/staticDropFiles/testConfigs.php

**Comment by akurtakov** [comment]
Helpdesk issue opened https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2392

**Comment by akurtakov** [comment]
@sravanlakkimsetti Can you help with this one https://ci.eclipse.org/releng/job/AutomatedTests/job/ep427I-unit-win32-java17/1/console ?

**Comment by iloveeclipse** [comment]
> I wonder if the directory where Java 11 was installed also had a space?

Nope: see https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/805/files
`-Djvm="C:\\\\openjdk\\\\jdk-11\\\\bin\\\\java.exe"`

**Comment by akurtakov** [comment]
@fredg02 can we get jdk-17 installed in a directory without space?

**Comment by iloveeclipse** [comment]
@akurtakov : why do we need `-Djvm`  argument at all? Can you please try without? AFAIK ant can find Java in the JAVA_HOME, if it is defined properly.

**Comment by sravanlakkimsetti** [comment]
> @sravanlakkimsetti Can you help with this one https://ci.eclipse.org/releng/job/AutomatedTests/job/ep427I-unit-win32-java17/1/console ?

When we have spaces in the paths we will need to use 8dot3 notation on windows. you get the name in 8dot3 notation using `dir /x`. 

Now the problem is fixed but I found another issue here. Ant installed on the test machine is quite old. because of that I had to keep JAVA_HOME as java 11 and use -Djvm with java 17

**Comment by akurtakov** [comment]
Would you please request update of Ant?

**Comment by sravanlakkimsetti** [comment]
> Would you please request update of Ant?

raised [Upgrade ant installed on https://ci.eclipse.org/releng/computer/qa6xd-win11/](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2502)
