### ISSUE TITLE
Inconsistencies of maven snapshots

### ISSUE THREAD

**Issue by cdietrich** [eclipse-platform/eclipse.platform.releng.aggregator#811]
https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/platform/org.eclipse.equinox.common/3.17.100-SNAPSHOT/
does not seems to have a snatshot jar for
3.17.100-SNAPSHOT:20230116.010608-15
thus my build fails with 
   > Could not find org.eclipse.equinox.common-3.17.100-SNAPSHOT.jar (org.eclipse.platform:org.eclipse.equinox.common:3.17.100-SNAPSHOT:20230116.010608-15).
     Searched in the following locations:
         https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/platform/org.eclipse.equinox.common/3.17.100-SNAPSHOT/org.eclipse.equinox.common-3.17.100-20230116.010608-15.jar
   > Could not find org.eclipse.osgi-3.18.300-SNAPSHOT.jar (org.eclipse.platform:org.eclipse.osgi:3.18.300-SNAPSHOT:20230116.013021-90).

any idea?

**Comment by cdietrich** [comment]
steps to reproduce

```
git clone https://github.com/eclipse/xtext-core.git
cd xtext-core
git checkout cd_platform427
./1-gradle-build.sh
```

**Comment by merks** [comment]
I haven't looked in detail, but I think when these things are being updated, nothing ensures that those updates are atomic so you could see things in an inconsistent state during the publishing period.

Look here:

https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/platform/org.eclipse.equinox.common/3.17.100-SNAPSHOT/maven-metadata.xml

the metadata contains this:
```
<metadata modelVersion="1.1.0">
<groupId>org.eclipse.platform</groupId>
<artifactId>org.eclipse.equinox.common</artifactId>
<versioning>
<lastUpdated>20230116010608</lastUpdated>
<snapshot>
<timestamp>20230116.010608</timestamp>
<buildNumber>15</buildNumber>
</snapshot>
<snapshotVersions>
<snapshotVersion>
<classifier>javadoc</classifier>
<extension>jar</extension>
<value>3.17.100-20230116.010608-15</value>
<updated>20230116010608</updated>
</snapshotVersion>
<snapshotVersion>
<extension>pom</extension>
<value>3.17.100-20230116.010608-15</value>
<updated>20230116010608</updated>
</snapshotVersion>
<snapshotVersion>
<extension>jar</extension>
<value>3.17.100-20230116.010550-14</value>
<updated>20230116010550</updated>
</snapshotVersion>
<snapshotVersion>
<classifier>sources</classifier>
<extension>jar</extension>
<value>3.17.100-20230115.012004-13</value>
<updated>20230115012004</updated>
</snapshotVersion>
</snapshotVersions>
</versioning>
<version>3.17.100-SNAPSHOT</version>
</metadata>
```

The corresponding artifacts for each classifier appears to be present:

- https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/platform/org.eclipse.equinox.common/3.17.100-SNAPSHOT/org.eclipse.equinox.common-3.17.100-20230116.010608-15-javadoc.jar
- https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/platform/org.eclipse.equinox.common/3.17.100-SNAPSHOT/org.eclipse.equinox.common-3.17.100-20230116.010608-15.pom
- https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/platform/org.eclipse.equinox.common/3.17.100-SNAPSHOT/org.eclipse.equinox.common-3.17.100-20230116.010550-14.jar
- https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/platform/org.eclipse.equinox.common/3.17.100-SNAPSHOT/org.eclipse.equinox.common-3.17.100-20230115.012004-13-sources.jar

The a org.eclipse.equinox.common-3.17.100-20230116.010608-15.jar resource does not exist but the metadata suggests it should be looking for org.eclipse.equinox.common-3.17.100-20230116.010550-14.jar instead.

The timestamps here seem to suggest this publishing was very recent (close to now).

Maybe the problem is no longer reproducible?

**Comment by cdietrich** [comment]
i still see the problem. maybe there is something bad with the artifacts gradle does not like.
is the stuff also published to sonatype snapshots?

**Comment by cdietrich** [comment]
i did not understand yet when the counter increases
in xtext we have the same id foreach ar
![Bildschirmfoto vom 2023-01-16 16-23-11](https://user-images.githubusercontent.com/238736/212713159-bfe88066-79ae-4083-a966-ea6589fb33b4.png)
tifacts (pom, jar, javadoc etc)

how are the artifacts deployed to nexus?

**Comment by cdietrich** [comment]
well. my dejavu brain is terrible. but it works
https://github.com/eclipse/lsp4j/issues/610

**Comment by merks** [comment]
I did not author the scripts. I think the same script is reused for nexus publishing.

**Comment by merks** [comment]
These multiple different calls is probably what causes the different version timestamps for the different artifacts I guess and that causes your problem.  Perhaps the code was written this way to be tolerant of missing source and javadoc and there are causes where those are missing because the IUs don't have Java source (I think for the doc bundles for example)...

It would be a significant time investment to try to change this but I guess without that these SNAPSHOTS are useless for you?

**Comment by cdietrich** [comment]
yes. i cannot continue testing as our builds will fail due to the timestamps. are milestones gonna be produced as well?

**Comment by merks** [comment]
This job produces SNAPSHOTS daily, mostly as a sanity test that when the final release is published that the job can be used to publish to Maven central.  So no, nothing different will be produced other than what you see now...

**Comment by cdietrich** [comment]
ok, otherwise i will test in march. we use old(er) platform artifacts in maven/gradle anyway

**Comment by merks** [comment]
With the new approach, the pom and the main artifact have the same `<value>` so I think that will solve your problem:
```
<metadata modelVersion="1.1.0">
<groupId>org.eclipse.platform</groupId>
<artifactId>org.eclipse.equinox.common</artifactId>
<versioning>
<lastUpdated>20230117130459</lastUpdated>
<snapshot>
<timestamp>20230117.130459</timestamp>
<buildNumber>21</buildNumber>
</snapshot>
<snapshotVersions>
<snapshotVersion>
<classifier>javadoc</classifier>
<extension>jar</extension>
<value>3.17.100-20230117.130459-21</value>
<updated>20230117130459</updated>
</snapshotVersion>
<snapshotVersion>
<extension>jar</extension>
<value>3.17.100-20230117.130459-20</value>
<updated>20230117130459</updated>
</snapshotVersion>
<snapshotVersion>
<extension>pom</extension>
<value>3.17.100-20230117.130459-20</value>
<updated>20230117130459</updated>
</snapshotVersion>
<snapshotVersion>
<classifier>sources</classifier>
<extension>jar</extension>
<value>3.17.100-20230115.012004-13</value>
<updated>20230115012004</updated>
</snapshotVersion>
</snapshotVersions>
</versioning>
<version>3.17.100-SNAPSHOT</version>
</metadata>
```
It's the best we can do...

Note that JDT publishing is currently failing:

https://ci.eclipse.org/releng/view/Publish%20to%20Maven/job/PublishJDTtoMaven/

though the artifacts are still being published, just some sources are missing pending this fix:

https://github.com/eclipse-platform/eclipse.platform.releng/pull/182

**Comment by merks** [comment]
@cdietrich Does this work now?

**Comment by cdietrich** [comment]
@merks no it does not
https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/platform/org.eclipse.core.runtime/
now seems to be empty

**Comment by merks** [comment]
There was a build failure last night, but I've kicked off a new one and will monitor it.  Thanks for the heads up!

**Comment by cdietrich** [comment]
here seems still to be a counting

<img width="1251" alt="Bildschirmfoto 2023-01-18 um 13 17 55" src="https://user-images.githubusercontent.com/238736/213169551-3af5e425-ea45-4593-81fc-e5fd98e23c12.png">

**Comment by cdietrich** [comment]
nope the build still seems trying to pull https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/platform/org.eclipse.core.runtime/3.26.100-SNAPSHOT/org.eclipse.core.runtime-3.26.100-20230118.115156-2.pom

**Comment by cdietrich** [comment]
@merks it still looks like you are still using the "too new/buggy" gpg:sign-and-deploy-file version

**Comment by merks** [comment]
@cdietrich 

This is there now:

https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/platform/org.eclipse.core.runtime/3.26.100-SNAPSHOT/

Maybe it works now?

**Comment by cdietrich** [comment]
@merks i assume it wont. this is why in lsp4j we had switch back to older version of the gpg:sign-and-deploy-file version plugin (as gradle uses the same identifier for all artifacts)

**Comment by cdietrich** [comment]
should we reopen @merks

**Comment by merks** [comment]
When I try to use that older version, it fails like this:
```
[INFO] --- maven-gpg-plugin:1.6:sign-and-deploy-file (default-cli) @ org.eclipse.releng.publish2maven ---
gpg: using "B414F87E" as default secret key for signing
gpg: signing failed: Inappropriate ioctl for device
gpg: signing failed: Inappropriate ioctl for device
```
I'll revert the change.  I'm not sure what else to do?  Maybe there is some version between the latest and 1.6 that works...

**Comment by cdietrich** [comment]
In. Xtext we use some special preconfigured to get it running https://github.com/eclipse/xtext-umbrella/commit/ac05cb2e00ebc77b8022c51d185a14eeaed5e71f

**Comment by merks** [comment]
The problem does look familiar relating to how the passphrase is processed where I think the failure is because it's trying to prompt from the terminal.  But I have no clue how to fix that in this set of scripts and pom and I have a limited capacity to chase this down, especially given that it looks like a gradle bug...

**Comment by cdietrich** [comment]
No issue. Just won’t be able to test any snapshots

**Comment by cdietrich** [comment]
found this one https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1226
