### ISSUE TITLE
Comparator errors in I20230307-0840

### ISSUE THREAD

**Issue by sravanlakkimsetti** [eclipse-platform/eclipse.platform.releng.aggregator#947]
Found the following comparator errors
1.  rt.equinox.p2/bundles/org.eclipse.equinox.p2.jarprocessor/.polyglot.META-INF
   no-classifier: different
      org/eclipse/equinox/internal/p2/jarprocessor/Utils.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

2.  eclipse.jdt.ui/org.eclipse.jdt.ui/pom.xml
   no-classifier: different
      org/eclipse/jdt/internal/ui/preferences/FilteredPreferenceTree.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

3.  eclipse.pde/ui/org.eclipse.pde.launching/.polyglot.META-INF
   no-classifier: different
      org/eclipse/pde/internal/launching/launcher/BundleLauncherHelper.class: different
    The main artifact has been replaced with the baseline version.
    The following attached artifacts have been replaced with the baseline version: [sources]

**Comment by sravanlakkimsetti** [comment]
Lambda order change.

**Comment by akurtakov** [comment]
Ah, app I used for comparison is broken as I use beta version. 
@iloveeclipse Isn't lambda order bug fixed already? I thought it is.

**Comment by iloveeclipse** [comment]
> Isn't lambda order bug fixed already? I thought it is.

Note: we haven't seen that in I builds for a long time.

This is a real mystery why **some** builds have that problem. 
Why building **same** code base fails with comparator errors now at release switch???
Could it be, we've changed ecj compiler version somehow?
Or may be because different maven/tycho version?

The problem with lambda generation was that if the code is compiled in a **different order**, the lambda's from one class may get different numbers in that class file. It's only about that numbers, not actual content. 

Assume class B has few lambdas in the code referenced by A and C classes. So if the maven/tycho/whoever decides to visit A, B, C classes in one build but C, B, A in another build, depending on which class is visited by compiler first, the lambdas in B may be generated in different order because in first round the code with lambda from B used by A was resolved first, and in the second case the code with lambda from B used by C.
